mongo:
  build: ./mongo
  ports:
   - "27017"
client:
  build: ./client
  volumes:
    - "./client/app:/src/app"
  env_file: .env
  environment:
    - MASTER_SERVER_PORT=2000
  ports:
    - "80:3000"
  restart: always
master:
  build: ./master
  volumes:
    - "./master/app:/src/app"
  env_file: .env
  environment:
    - SESSION_SECRET=potatoesec
    - PORT=2000
  links: 
    - mongo
  ports:
    - "2000:3000"
  restart: always
server:
  build: ./server
  volumes:
    - "./server/app:/src/app"
  env_file: .env
  environment:
    - SESSION_SECRET=potatoesec
    - PORT=2001
    - MASTER_SERVER_PORT=2000
  links: 
    - mongo
  ports:
    - "2001:3000"
  restart: always
server2:
  build: ./server
  volumes:
    - "./server/app:/src/app"
  env_file: .env
  environment:
    - SESSION_SECRET=potatoesec
    - PORT=2002
    - MASTER_SERVER_PORT=2000
  links: 
    - mongo
  ports:
    - "2002:3000"
  restart: always
server3:
  build: ./server
  volumes:
    - "./server/app:/src/app"
  env_file: .env
  environment:
    - SESSION_SECRET=potatoesec
    - PORT=2003
    - MASTER_SERVER_PORT=2000
  links: 
    - mongo
  ports:
    - "2003:3000"
  restart: always